import React from 'react';
import { BenchmarkChart, BenchmarkData } from './BenchmarkChart';
import './App.css';
import githubLogo from './github-logo.svg';

// Sample data representing benchmark results. In a real application, this would be fetched from an API.
const simpleTransferData: BenchmarkData = {
  labels: ["100", "200", "400", "800", "1600", "3200"],
  datasets: [
    {
      label: 'TPS (Transactions Per Second)',
      data: [95, 185, 370, 710, 1250, 1310],
      borderColor: 'rgb(75, 192, 192)',
      backgroundColor: 'rgba(75, 192, 192, 0.5)',
      yAxisID: 'y',
    },
    {
      label: 'Avg Latency (ms)',
      data: [150, 180, 210, 250, 350, 550],
      borderColor: 'rgb(255, 99, 132)',
      backgroundColor: 'rgba(255, 99, 132, 0.5)',
      yAxisID: 'y1',
    },
  ],
};

const multiPartyData: BenchmarkData = {
  labels: ["50", "100", "200", "400", "800", "1600"],
  datasets: [
    {
      label: 'TPS (Transactions Per Second)',
      data: [48, 92, 175, 330, 580, 610],
      borderColor: 'rgb(54, 162, 235)',
      backgroundColor: 'rgba(54, 162, 235, 0.5)',
      yAxisID: 'y',
    },
    {
      label: 'Avg Latency (ms)',
      data: [220, 260, 310, 380, 520, 850],
      borderColor: 'rgb(255, 159, 64)',
      backgroundColor: 'rgba(255, 159, 64, 0.5)',
      yAxisID: 'y1',
    },
  ],
};

const sequencerSaturationData: BenchmarkData = {
    labels: ["1k", "2k", "4k", "8k", "16k", "32k"],
    datasets: [
      {
        label: 'Ingress Rate (msgs/sec)',
        data: [1000, 2000, 4000, 8000, 15500, 28000],
        borderColor: 'rgb(153, 102, 255)',
        backgroundColor: 'rgba(153, 102, 255, 0.5)',
        yAxisID: 'y',
      },
      {
        label: 'Backpressure Latency (ms)',
        data: [5, 10, 25, 80, 400, 1200],
        borderColor: 'rgb(255, 205, 86)',
        backgroundColor: 'rgba(255, 205, 86, 0.5)',
        yAxisID: 'y1',
      },
    ],
  };


function App() {
  return (
    <div className="App">
      <header className="App-header">
        <h1>Canton Network Load Testing Benchmarks</h1>
        <p className="subtitle">
          Independent, open-source performance metrics for institutional due diligence.
        </p>
      </header>

      <main className="App-main">
        <section className="intro-section">
          <h2>About These Benchmarks</h2>
          <p>
            This dashboard presents the results from the Canton Load Testing Suite, an open-source
            framework designed to provide transparent and verifiable throughput data for the Canton Network.
            Unlike marketing claims, these figures are generated by publicly available, configurable workloads
            that simulate real-world financial scenarios. The entire testing suite, from Daml models to the
            Go-based test runner, is available on GitHub for independent review and execution.
          </p>
          <p>
            Our goal is to empower institutions, developers, and the community to make informed decisions
            based on empirical data about Canton's scalability and performance characteristics.
          </p>
        </section>

        <div className="benchmarks-container">
          <div className="benchmark-card">
            <h3>Simple P2P Transfer (UTXO Model)</h3>
            <p className="benchmark-description">
              Measures the throughput of simple, two-party asset transfers. This represents a foundational workload for many financial applications, testing the core UTXO model performance and ledger concurrency under increasing load (Concurrent In-Flight Transactions).
            </p>
            <BenchmarkChart
              data={simpleTransferData}
              title="TPS vs. Latency under Concurrent In-Flight Transactions"
              xAxisLabel="Concurrent In-Flight Transactions"
            />
          </div>

          <div className="benchmark-card">
            <h3>Multi-Party Settlement (DvP)</h3>
            <p className="benchmark-description">
              Simulates a Delivery-vs-Payment (DvP) scenario involving four distinct parties per transaction (e.g., buyer, seller, CSD, payment agent). This benchmark stresses the Canton protocol's ability to coordinate complex, atomic, multi-domain workflows while maintaining privacy.
            </p>
            <BenchmarkChart
              data={multiPartyData}
              title="TPS vs. Latency for 4-Party DvP"
              xAxisLabel="Concurrent In-Flight Transactions"
            />
          </div>

          <div className="benchmark-card">
            <h3>Sequencer Saturation Test</h3>
            <p className="benchmark-description">
              This test measures the raw ingress capacity of the Canton Sequencer, a critical component for ordering and timestamping transactions. It sends a high volume of minimal-sized messages to identify the maximum sustainable message rate before backpressure significantly increases latency.
            </p>
            <BenchmarkChart
              data={sequencerSaturationData}
              title="Sequencer Ingress Rate vs. Backpressure Latency"
              xAxisLabel="Target Ingress Rate (messages/sec)"
            />
          </div>
        </div>
      </main>

      <footer className="App-footer">
        <a
          href="https://github.com/digital-asset/canton-load-testing"
          target="_blank"
          rel="noopener noreferrer"
        >
          <img src={githubLogo} alt="GitHub Logo" className="github-logo" />
          View on GitHub
        </a>
        <p>
          All tests run on Canton v3.4.0 with default participant and sequencer configurations.
        </p>
      </footer>
    </div>
  );
}

export default App;